// Package dlp: behavioral.go — Behavioral detection engine for DLP.
//
// Detects data exfiltration patterns that regex-based content scanning misses:
//
//   RuleMassFileAccess    — A single process reads an unusually large number of
//                           files in a short time window (staging / enumeration).
//   RuleBulkRead          — A process reads more than BulkReadThresholdMB of data
//                           within the detection window (bulk exfil preparation).
//   RuleUSBBulkCopy       — A process writes more than USBCopyThreshold files to
//                           removable media within the window.
//   RuleArchiveCreation   — A process creates a ZIP/tar/7z archive; combined with
//                           DLP matches → high-confidence staging alert.
//   RuleCloudUpload       — A known cloud-sync process (rclone, gdrive, etc.) is
//                           observed performing file writes.
//   RuleInsiderThreat     — After-hours bulk file access by a non-service account
//                           (heuristic for insider threat; escalate for analyst review).
//
// ML integration:
//   All detections feed a BehavioralFeatures struct. Register an MLScoringHook
//   implementation to plug in a custom model (ONNX runtime, Python gRPC, etc.).
//   The default NoOpMLHook returns a zero risk score and is a safe placeholder.
package dlp

import (
	"fmt"
	"strings"
	"sync"
	"time"
)

// ─────────────────────────────────────────────────────────────────────────────
// Rule identifiers
// ─────────────────────────────────────────────────────────────────────────────

const (
	RuleMassFileAccess  = "dlp_mass_file_access"
	RuleBulkRead        = "dlp_bulk_read"
	RuleUSBBulkCopy     = "dlp_usb_bulk_copy"
	RuleArchiveCreation = "dlp_archive_creation"
	RuleCloudUpload     = "dlp_cloud_upload"
	RuleInsiderThreat   = "dlp_insider_threat"
)

// archiveExtensions lists file extensions that indicate archive creation.
var archiveExtensions = []string{
	".zip", ".tar", ".gz", ".tgz", ".7z", ".bz2", ".rar", ".xz", ".zst",
}

// ─────────────────────────────────────────────────────────────────────────────
// BehavioralAlert
// ─────────────────────────────────────────────────────────────────────────────

// BehavioralAlert is generated by the BehavioralEngine when a rule fires.
type BehavioralAlert struct {
	// Rule is the rule identifier (e.g. RuleMassFileAccess).
	Rule string `json:"rule"`

	// Pid is the offending process ID.
	Pid uint32 `json:"pid"`

	// Uid is the user ID of the process.
	Uid uint32 `json:"uid"`

	// ProcessName is the process comm string.
	ProcessName string `json:"process_name"`

	// Detail is a human-readable description of what triggered the rule.
	Detail string `json:"detail"`

	// Severity of the behavioral alert: "medium", "high", "critical".
	Severity string `json:"severity"`

	// Channel identifies the relevant DLP channel (e.g. ChannelUSB).
	Channel Channel `json:"channel,omitempty"`

	// MitreAttck lists applicable MITRE ATT&CK technique IDs.
	MitreAttck []string `json:"mitre_attck,omitempty"`

	// MLRiskScore is the score returned by the registered MLScoringHook, [0.0, 1.0].
	MLRiskScore float64 `json:"ml_risk_score,omitempty"`

	// Timestamp when the alert was generated.
	Timestamp time.Time `json:"timestamp"`
}

// ─────────────────────────────────────────────────────────────────────────────
// ML integration interface
// ─────────────────────────────────────────────────────────────────────────────

// BehavioralFeatures is the feature vector passed to ML scoring models.
// Fields are designed to be compatible with common ML frameworks (scikit-learn,
// ONNX, TensorFlow). All numeric features use float64 for maximum compatibility.
type BehavioralFeatures struct {
	// Process identity
	Pid         uint32 `json:"pid"`
	Uid         uint32 `json:"uid"`
	ProcessName string `json:"process_name"`

	// File access features (rolling 60-second window)
	FilesAccessed1m   int     `json:"files_accessed_1m"`
	FilesAccessed5m   int     `json:"files_accessed_5m"`
	BytesReadMB       float64 `json:"bytes_read_mb"`
	UniqueExtensions  int     `json:"unique_extensions"`
	SensitiveFileHits int     `json:"sensitive_file_hits"` // DLP pattern matches in window

	// USB features
	USBFilesWritten1m  int     `json:"usb_files_written_1m"`
	USBBytesWrittenMB  float64 `json:"usb_bytes_written_mb"`

	// Network/cloud features
	OutboundConnections1m int  `json:"outbound_connections_1m"`
	IsCloudProcess        bool `json:"is_cloud_process"`

	// Archive features
	ArchivesCreated1m int `json:"archives_created_1m"`

	// Temporal features
	HourOfDay    int  `json:"hour_of_day"`    // 0–23
	IsWeekend    bool `json:"is_weekend"`
	IsAfterHours bool `json:"is_after_hours"` // outside 08:00–18:00 weekdays

	// Context
	Timestamp time.Time `json:"timestamp"`
	HostID    string    `json:"host_id,omitempty"`
	TenantID  string    `json:"tenant_id,omitempty"`
}

// MLScoringHook is the interface for plugging in ML anomaly detection models.
// Implement this interface to enable AI-driven insider-threat scoring.
//
// Example integration: gRPC call to a Python inference service, ONNX runtime
// binding, or an in-process statistical model.
type MLScoringHook interface {
	// Score receives a feature vector and returns a risk score [0.0, 1.0]
	// and a human-readable reason string.
	Score(features BehavioralFeatures) (riskScore float64, reason string)
}

// NoOpMLHook is the default placeholder implementation.
// Register a real implementation via BehavioralEngine.SetMLHook().
type NoOpMLHook struct{}

func (n *NoOpMLHook) Score(_ BehavioralFeatures) (float64, string) {
	return 0.0, "ml_scoring_not_configured"
}

// ─────────────────────────────────────────────────────────────────────────────
// Per-process tracking state
// ─────────────────────────────────────────────────────────────────────────────

// fileAccessEvent records one file-read event for rate tracking.
type fileAccessEvent struct {
	ts        time.Time
	path      string
	sizeBytes int64
}

// usbWriteEvent records one file-write-to-USB event for rate tracking.
type usbWriteEvent struct {
	ts        time.Time
	path      string
	sizeBytes int64
}

// pidTracker accumulates DLP-relevant activity for a single process.
type pidTracker struct {
	pid         uint32
	uid         uint32
	processName string

	// Sliding window of file access events.
	fileAccesses []fileAccessEvent

	// Sliding window of USB write events.
	usbWrites []usbWriteEvent

	// Archive files created in this window.
	archivesCreated []time.Time

	// Sensitive pattern hit count in this window.
	sensitiveHits int

	// Unique extensions seen in this window.
	extensions map[string]struct{}

	// Outbound network connection timestamps.
	outboundConns []time.Time
}

// ─────────────────────────────────────────────────────────────────────────────
// BehavioralEngine
// ─────────────────────────────────────────────────────────────────────────────

// BehavioralEngine tracks per-process DLP-relevant activity and fires alerts
// when thresholds are exceeded. It is safe for concurrent use.
//
// The engine uses a sliding window model: events older than the window are
// discarded on each check, keeping memory use bounded.
type BehavioralEngine struct {
	mu sync.Mutex

	// Per-process state map; pruned when process exits or on overflow.
	pids map[uint32]*pidTracker

	// Maximum number of simultaneously tracked processes.
	maxPIDs int

	// Detection window duration.
	window time.Duration

	// Thresholds — all configurable via SetThresholds().
	massAccessThreshold int // max files/window before RuleMassFileAccess fires
	bulkReadThresholdMB int // max MB read/window before RuleBulkRead fires
	usbCopyThreshold    int // max USB files/window before RuleUSBBulkCopy fires

	// ML scoring hook. Defaults to NoOpMLHook.
	mlHook MLScoringHook

	// Pending alerts (drained by DrainAlerts).
	alerts []BehavioralAlert
}

// NewBehavioralEngine creates a behavioral engine with sensible enterprise defaults.
func NewBehavioralEngine() *BehavioralEngine {
	return &BehavioralEngine{
		pids:                make(map[uint32]*pidTracker),
		maxPIDs:             8192,
		window:              60 * time.Second,
		massAccessThreshold: 100,  // >100 files/60s = suspicious
		bulkReadThresholdMB: 50,   // >50 MB read in 60s = suspicious
		usbCopyThreshold:    20,   // >20 files to USB in 60s = suspicious
		mlHook:              &NoOpMLHook{},
	}
}

// SetThresholds overrides the default detection thresholds.
//   massAccess: max file accesses per window (default 100)
//   bulkReadMB: max MB read per window (default 50)
//   usbCopy:    max USB writes per window (default 20)
func (e *BehavioralEngine) SetThresholds(massAccess, bulkReadMB, usbCopy int) {
	e.mu.Lock()
	defer e.mu.Unlock()
	if massAccess > 0 {
		e.massAccessThreshold = massAccess
	}
	if bulkReadMB > 0 {
		e.bulkReadThresholdMB = bulkReadMB
	}
	if usbCopy > 0 {
		e.usbCopyThreshold = usbCopy
	}
}

// SetMLHook registers an ML scoring implementation.
// Pass nil to revert to the NoOpMLHook.
func (e *BehavioralEngine) SetMLHook(hook MLScoringHook) {
	e.mu.Lock()
	defer e.mu.Unlock()
	if hook == nil {
		e.mlHook = &NoOpMLHook{}
	} else {
		e.mlHook = hook
	}
}

// RecordFileAccess records that a process read a file. Call this from the file
// event loop (openat / write monitor) for every DLP-relevant file operation.
//
//   pid:       process ID
//   uid:       user ID
//   comm:      process name
//   path:      absolute file path
//   sizeBytes: file size in bytes (0 if unknown)
func (e *BehavioralEngine) RecordFileAccess(pid, uid uint32, comm, path string, sizeBytes int64) {
	e.mu.Lock()
	defer e.mu.Unlock()
	t := e.getOrCreateTracker(pid, uid, comm)
	t.fileAccesses = append(t.fileAccesses, fileAccessEvent{
		ts:        time.Now(),
		path:      path,
		sizeBytes: sizeBytes,
	})
	ext := strings.ToLower(getExtension(path))
	if ext != "" {
		t.extensions[ext] = struct{}{}
	}
}

// RecordUSBWrite records that a process wrote a file to removable media.
func (e *BehavioralEngine) RecordUSBWrite(pid, uid uint32, comm, path string, sizeBytes int64) {
	e.mu.Lock()
	defer e.mu.Unlock()
	t := e.getOrCreateTracker(pid, uid, comm)
	t.usbWrites = append(t.usbWrites, usbWriteEvent{
		ts:        time.Now(),
		path:      path,
		sizeBytes: sizeBytes,
	})
}

// RecordArchiveCreation records that a process created an archive file.
// Triggers RuleArchiveCreation, especially when combined with prior DLP hits.
func (e *BehavioralEngine) RecordArchiveCreation(pid, uid uint32, comm, path string) {
	e.mu.Lock()
	defer e.mu.Unlock()
	ext := strings.ToLower(getExtension(path))
	for _, archExt := range archiveExtensions {
		if ext == archExt {
			t := e.getOrCreateTracker(pid, uid, comm)
			t.archivesCreated = append(t.archivesCreated, time.Now())
			return
		}
	}
}

// RecordOutboundConnection records that a process made an outbound network connection.
func (e *BehavioralEngine) RecordOutboundConnection(pid, uid uint32, comm string) {
	e.mu.Lock()
	defer e.mu.Unlock()
	t := e.getOrCreateTracker(pid, uid, comm)
	t.outboundConns = append(t.outboundConns, time.Now())
}

// RecordSensitiveHit records that a DLP pattern matched for this process.
// This increments the counter used by the ML feature vector.
func (e *BehavioralEngine) RecordSensitiveHit(pid, uid uint32, comm string) {
	e.mu.Lock()
	defer e.mu.Unlock()
	t := e.getOrCreateTracker(pid, uid, comm)
	t.sensitiveHits++
}

// RemovePID removes tracking state for a process (call on process exit).
func (e *BehavioralEngine) RemovePID(pid uint32) {
	e.mu.Lock()
	defer e.mu.Unlock()
	delete(e.pids, pid)
}

// Check evaluates all tracked processes against behavioral rules and returns
// any new alerts. It also prunes expired events from all trackers.
// Call this periodically (e.g. every 5 seconds) or after any RecordXxx call.
func (e *BehavioralEngine) Check() []BehavioralAlert {
	e.mu.Lock()
	defer e.mu.Unlock()

	now := time.Now()
	cutoff := now.Add(-e.window)
	var newAlerts []BehavioralAlert

	for pid, t := range e.pids {
		// Prune events outside the sliding window.
		t.fileAccesses = pruneFileAccesses(t.fileAccesses, cutoff)
		t.usbWrites = pruneUSBWrites(t.usbWrites, cutoff)
		t.archivesCreated = pruneTimestamps(t.archivesCreated, cutoff)
		t.outboundConns = pruneTimestamps(t.outboundConns, cutoff)

		// Remove idle trackers (nothing in window) to bound memory.
		if len(t.fileAccesses) == 0 && len(t.usbWrites) == 0 &&
			len(t.archivesCreated) == 0 && len(t.outboundConns) == 0 {
			delete(e.pids, pid)
			continue
		}

		features := e.buildFeatures(t, now)

		// --- Rule: Mass File Access ---
		if len(t.fileAccesses) >= e.massAccessThreshold {
			newAlerts = append(newAlerts, BehavioralAlert{
				Rule:        RuleMassFileAccess,
				Pid:         pid,
				Uid:         t.uid,
				ProcessName: t.processName,
				Severity:    "high",
				Detail: fmt.Sprintf(
					"process %q (pid=%d uid=%d) accessed %d files in %s (threshold %d)",
					t.processName, pid, t.uid,
					len(t.fileAccesses), e.window, e.massAccessThreshold,
				),
				MitreAttck: []string{"T1005", "T1074"}, // Data from Local System, Data Staged
				MLRiskScore: e.scoreML(features),
				Timestamp:  now,
			})
		}

		// --- Rule: Bulk Read ---
		var totalBytes int64
		for _, fa := range t.fileAccesses {
			totalBytes += fa.sizeBytes
		}
		totalMB := float64(totalBytes) / (1024 * 1024)
		if totalMB >= float64(e.bulkReadThresholdMB) {
			newAlerts = append(newAlerts, BehavioralAlert{
				Rule:        RuleBulkRead,
				Pid:         pid,
				Uid:         t.uid,
				ProcessName: t.processName,
				Severity:    "high",
				Detail: fmt.Sprintf(
					"process %q (pid=%d) read %.1f MB in %s (threshold %d MB)",
					t.processName, pid, totalMB, e.window, e.bulkReadThresholdMB,
				),
				MitreAttck:  []string{"T1005", "T1074"},
				MLRiskScore: e.scoreML(features),
				Timestamp:   now,
			})
		}

		// --- Rule: USB Bulk Copy ---
		if len(t.usbWrites) >= e.usbCopyThreshold {
			var usbBytes int64
			for _, uw := range t.usbWrites {
				usbBytes += uw.sizeBytes
			}
			newAlerts = append(newAlerts, BehavioralAlert{
				Rule:        RuleUSBBulkCopy,
				Pid:         pid,
				Uid:         t.uid,
				ProcessName: t.processName,
				Severity:    "critical",
				Channel:     ChannelUSB,
				Detail: fmt.Sprintf(
					"process %q (pid=%d uid=%d) copied %d files (%.1f MB) to USB in %s",
					t.processName, pid, t.uid,
					len(t.usbWrites), float64(usbBytes)/(1024*1024), e.window,
				),
				MitreAttck:  []string{"T1052"}, // Exfiltration Over Physical Medium
				MLRiskScore: e.scoreML(features),
				Timestamp:   now,
			})
		}

		// --- Rule: Archive Creation (with sensitive file context) ---
		if len(t.archivesCreated) > 0 && t.sensitiveHits > 0 {
			newAlerts = append(newAlerts, BehavioralAlert{
				Rule:        RuleArchiveCreation,
				Pid:         pid,
				Uid:         t.uid,
				ProcessName: t.processName,
				Severity:    "high",
				Detail: fmt.Sprintf(
					"process %q (pid=%d) created %d archive(s) after %d sensitive file hit(s)",
					t.processName, pid, len(t.archivesCreated), t.sensitiveHits,
				),
				MitreAttck:  []string{"T1560"}, // Archive Collected Data
				MLRiskScore: e.scoreML(features),
				Timestamp:   now,
			})
		}

		// --- Rule: Cloud Upload (known cloud-sync process + outbound traffic) ---
		if IsCloudStorageProcess(t.processName) && len(t.outboundConns) > 0 {
			newAlerts = append(newAlerts, BehavioralAlert{
				Rule:        RuleCloudUpload,
				Pid:         pid,
				Uid:         t.uid,
				ProcessName: t.processName,
				Severity:    "high",
				Channel:     ChannelCloudStorage,
				Detail: fmt.Sprintf(
					"cloud-sync process %q (pid=%d) made %d outbound connection(s)",
					t.processName, pid, len(t.outboundConns),
				),
				MitreAttck:  []string{"T1567"}, // Exfiltration Over Web Service
				MLRiskScore: e.scoreML(features),
				Timestamp:   now,
			})
		}

		// --- Rule: Insider Threat (after-hours bulk access) ---
		h := now.Hour()
		isAfterHours := h < 8 || h >= 18
		isWeekend := now.Weekday() == time.Saturday || now.Weekday() == time.Sunday
		if (isAfterHours || isWeekend) &&
			len(t.fileAccesses) >= e.massAccessThreshold/2 &&
			t.uid >= 1000 { // skip service accounts (uid < 1000)
			newAlerts = append(newAlerts, BehavioralAlert{
				Rule:        RuleInsiderThreat,
				Pid:         pid,
				Uid:         t.uid,
				ProcessName: t.processName,
				Severity:    "critical",
				Detail: fmt.Sprintf(
					"after-hours bulk access: process %q (pid=%d uid=%d) accessed %d files at %s (weekend=%v)",
					t.processName, pid, t.uid, len(t.fileAccesses), now.Format("15:04"), isWeekend,
				),
				MitreAttck:  []string{"T1005", "T1074"},
				MLRiskScore: e.scoreML(features),
				Timestamp:   now,
			})
		}
	}

	e.alerts = append(e.alerts, newAlerts...)
	return newAlerts
}

// DrainAlerts returns and clears all accumulated behavioral alerts.
func (e *BehavioralEngine) DrainAlerts() []BehavioralAlert {
	e.mu.Lock()
	defer e.mu.Unlock()
	out := e.alerts
	e.alerts = nil
	return out
}

// ─────────────────────────────────────────────────────────────────────────────
// Internal helpers
// ─────────────────────────────────────────────────────────────────────────────

// getOrCreateTracker returns or creates the pidTracker for pid (caller holds mu).
func (e *BehavioralEngine) getOrCreateTracker(pid, uid uint32, comm string) *pidTracker {
	if t, ok := e.pids[pid]; ok {
		return t
	}
	if len(e.pids) >= e.maxPIDs {
		// Evict one idle entry to keep memory bounded.
		for id := range e.pids {
			delete(e.pids, id)
			break
		}
	}
	t := &pidTracker{
		pid:         pid,
		uid:         uid,
		processName: comm,
		extensions:  make(map[string]struct{}),
	}
	e.pids[pid] = t
	return t
}

// buildFeatures constructs the ML feature vector from the current tracker state.
func (e *BehavioralEngine) buildFeatures(t *pidTracker, now time.Time) BehavioralFeatures {
	var totalBytes int64
	for _, fa := range t.fileAccesses {
		totalBytes += fa.sizeBytes
	}
	var usbBytes int64
	for _, uw := range t.usbWrites {
		usbBytes += uw.sizeBytes
	}
	h := now.Hour()
	return BehavioralFeatures{
		Pid:                   t.pid,
		Uid:                   t.uid,
		ProcessName:           t.processName,
		FilesAccessed1m:       len(t.fileAccesses),
		BytesReadMB:           float64(totalBytes) / (1024 * 1024),
		UniqueExtensions:      len(t.extensions),
		SensitiveFileHits:     t.sensitiveHits,
		USBFilesWritten1m:     len(t.usbWrites),
		USBBytesWrittenMB:     float64(usbBytes) / (1024 * 1024),
		OutboundConnections1m: len(t.outboundConns),
		IsCloudProcess:        IsCloudStorageProcess(t.processName),
		ArchivesCreated1m:     len(t.archivesCreated),
		HourOfDay:             h,
		IsWeekend:             now.Weekday() == time.Saturday || now.Weekday() == time.Sunday,
		IsAfterHours:          h < 8 || h >= 18,
		Timestamp:             now,
	}
}

// scoreML calls the registered ML hook and returns the risk score.
// Panics are recovered and result in a 0.0 score.
func (e *BehavioralEngine) scoreML(f BehavioralFeatures) (score float64) {
	defer func() {
		if r := recover(); r != nil {
			score = 0.0
		}
	}()
	score, _ = e.mlHook.Score(f)
	return score
}

// pruneFileAccesses removes events older than cutoff.
func pruneFileAccesses(events []fileAccessEvent, cutoff time.Time) []fileAccessEvent {
	i := 0
	for i < len(events) && events[i].ts.Before(cutoff) {
		i++
	}
	return events[i:]
}

// pruneUSBWrites removes events older than cutoff.
func pruneUSBWrites(events []usbWriteEvent, cutoff time.Time) []usbWriteEvent {
	i := 0
	for i < len(events) && events[i].ts.Before(cutoff) {
		i++
	}
	return events[i:]
}

// pruneTimestamps removes timestamps older than cutoff.
func pruneTimestamps(ts []time.Time, cutoff time.Time) []time.Time {
	i := 0
	for i < len(ts) && ts[i].Before(cutoff) {
		i++
	}
	return ts[i:]
}

// getExtension returns the lowercase extension of path (e.g. ".zip").
func getExtension(path string) string {
	for i := len(path) - 1; i >= 0; i-- {
		if path[i] == '.' {
			return path[i:]
		}
		if path[i] == '/' {
			break
		}
	}
	return ""
}
